### ISSUE TITLE
이미지 저장 기능 추가

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#13]
## Description
피드백 내용: 나중에 이미지 저장 기능도 있으면 좋을 것 같아요...! 캡쳐도 되지만 이렇게 예쁜 디자인이 주소창이랑 찍히는게 아쉬워서요

## Todo
- [x] 빙고판 이미지 저장 기능 추가.
- [x] 이미지 저장 시 이미지 이름을 타이틀로 바꾸기.
- [x] 투표 결과대로 주변 여백 보이게 화면을 캡처해서 저장할 수 있도록 만들기.
- [x]  UI를 적절하게 수정.

**Comment by robinyoon-dev** [comment]
# 투표 결과
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/3c54d304-1153-419c-975a-08dfd1c8d8b6)

득표수 1위
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/348c8e16-289f-476b-bfb7-46ea1c673d81)

득표수 2위
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/3ab6e2e3-6d00-4394-ad6d-c80385bcbf32)

**Comment by robinyoon-dev** [comment]
# `canvas` 태그 자료
http://www.tcpschool.com/html-tags/canvas

http://www.tcpschool.com/html/html5_graphic_canvas

[CanvasRenderingContext2D.drawWindow()](https://runebook.dev/ko/docs/dom/canvasrenderingcontext2d/drawwindow)

[Canvas with React](https://medium.com/@pdx.lucasm/canvas-with-react-js-32e133c05258)

[[React] React에서 Canvas 사용하기(마우스로 그리기)](https://velog.io/@mokyoungg/React-React%EC%97%90%EC%84%9C-Canvas-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0%EB%A7%88%EC%9A%B0%EC%8A%A4-%EA%B7%B8%EB%A6%AC%EA%B8%B0)

[html2canvas](https://html2canvas.hertzen.com/)

**Comment by robinyoon-dev** [comment]
# 문제 : `divRef.current`가 `null`로 나온다.
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/8e01dba2-de5a-46e8-8d33-1894ba03ef64)

전체 코드
```javascript
import { MongoClient, ObjectId } from "mongodb";
import ShareBoard from "@/components/boards/ShareBoard";
import Layout from "@/components/layout/Layout";
import { useState, useEffect, useRef } from "react";
import styles from "@/styles/style.module.css";
import Link from "next/link";
import Grid from "@/components/layout/Grid";
import LoadingSpinner from "@/components/parts/LoadingSpinner";
import Head from "next/head";
import Confetti from "@/components/parts/Confetti";
import config from "@/config/mongo.config";
function SharePage({ newBoard, bingoData, data }) {
  const [showCopiedMessage, setShowCopiedMessage] = useState(false);

  const [isLoading, setIsLoading] = useState(true);

  const divRef = useRef(null);
  const canvasRef = useRef(null);

  useEffect(() => {
    if (data !== null) {
      setIsLoading(false);
    }
  }, []);

  if (isLoading) {
    return <LoadingSpinner />;
  }

  const bingoUrl = getBingoUrl(bingoData);

  const shareUrl = `https://planbingo.vercel.app/fromLink?id=${data.id}${bingoUrl}`;

  const handleCopyClick = () => {
    navigator.clipboard.writeText(shareUrl);
    setShowCopiedMessage(true);
  };

  const downloadCanvasDiv = () => {
    const div = divRef.current;
    const canvas = canvasRef.current;

    console.log("-----div----");
    console.log(div);
    canvas.width = div.offsetWidth;
    canvas.height = div.offsetHeight;

    const context = canvas.getContext("2d");

    context.drawWindow(
      window,
      div.offsetLeft,
      div.offsetTop,
      div.offsetWidth,
      div.offsetHeight,
      "rgb(255, 255, 255)"
    );

    const dataURL = canvas.toDataURL("image/png");

    const link = document.createElement("a");
    link.href = dataURL;
    link.download = "div_image.png";
    link.click();
  };

  return (
    <>
      <Head>
        <title>플랜 빙고</title>
      </Head>

      <Layout>
        {newBoard.newBoard && <Confetti />}
        {data.bingoCount === 8 && <Confetti />}
        {newBoard.newBoard && (
          <div className={styles.fontSize}>
            처음으로 플랜 빙고를 만들었어요!
          </div>
        )}
        {newBoard.newBoard === false && data.bingoCount !== 8 && (
          <div className={styles.fontSize}> 👏목표를 달성했군요!👏</div>
        )}
        {data.bingoCount === 8 && (
          <div className={styles.fontSize}>
            {" "}
            🎉축하합니다! 빙고를 완성했어요!🎉
          </div>
        )}

        <canvas ref={canvasRef}></canvas>

        <div ref={divRef}>
          <ShareBoard
            bingoData={bingoData}
            main={data.main}
            title={data.title}
            value1={data.value1}
            value2={data.value2}
            value3={data.value3}
            value4={data.value4}
            value5={data.value5}
            value6={data.value6}
            value7={data.value7}
            value8={data.value8}
            value9={data.value9}
            bgColor={data.bgColor}
            cubeColor={data.cubeColor}
            bingoCount={data.bingoCount}
            patternArray={data.patternArray}
          />
        </div>

        {newBoard.newBoard && (
          <div className={styles.fontSizeS}>목표를 공유해볼까요?</div>
        )}
        {newBoard.newBoard === false && data.bingoCount !== 8 && (
          <div className={styles.fontSizeS}> 플랜 빙고를 공유해봐요😊</div>
        )}
        {data.bingoCount === 8 && (
          <div className={styles.fontSizeS}>
            {" "}
            완성한 플랜 빙고를 자랑해봐요!
          </div>
        )}

        <button onClick={downloadCanvasDiv()}>이미지 저장하기</button>

        {showCopiedMessage && (
          <div className={styles.alarm}>링크가 복사되었습니다!</div>
        )}
        <Grid>
          <Link
            className={[styles.button, styles.btnNoneColor].join(" ")}
            href="/home"
          >
            홈으로
          </Link>

          <button
            onClick={handleCopyClick}
            className={[styles.button, styles.btnColor].join(" ")}
          >
            링크 복사하기
          </button>
        </Grid>
      </Layout>
    </>
  );
}

export async function getServerSideProps(ctx) {
  let newBoard, bingoData, data;

  if (ctx.query.bingoData) {
    bingoData = JSON.parse(ctx.query.bingoData);
  } else {
    bingoData = {
      bingo123: false,
      bingo456: false,
      bingo789: false,
      bingo147: false,
      bingo258: false,
      bingo369: false,
      bingo159: false,
      bingo357: false,
    };
  }

  data = JSON.parse(ctx.query.data);

  if (data.newBoard) {
    newBoard = true;
  } else {
    newBoard = false;
  }

  // fetch data from an API
  const client = await MongoClient.connect(config.mongoClient);
  const db = client.db();

  const boardsCollection = db.collection("boards");

  const board = await boardsCollection.findOne({ _id: ObjectId(data._id) });

  client.close();

  return {
    props: {
      newBoard: {
        newBoard,
      },
      bingoData: {
        bingo123: bingoData.bingo123,
        bingo456: bingoData.bingo456,
        bingo789: bingoData.bingo789,
        bingo147: bingoData.bingo147,
        bingo258: bingoData.bingo258,
        bingo369: bingoData.bingo369,
        bingo159: bingoData.bingo159,
        bingo357: bingoData.bingo357,
      },
      data: {
        id: board._id.toString(),
        user: board.user,
        main: board.main,
        title: board.title,
        value1: board.value1,
        value2: board.value2,
        value3: board.value3,
        value4: board.value4,
        value5: board.value5,
        value6: board.value6,
        value7: board.value7,
        value8: board.value8,
        value9: board.value9,
        bgColor: board.bgColor,
        cubeColor: board.cubeColor,
        bingoCount: board.bingoCount,
        patternArray: board.patternArray,
      },
    },
  };
}

export function getBingoUrl(bingoData) {
  const bingoNumbers = [
    "bingo123",
    "bingo456",
    "bingo789",
    "bingo147",
    "bingo258",
    "bingo369",
    "bingo159",
    "bingo357",
  ];

  const tempArray = bingoNumbers.map((bingoNumber) => {
    if (bingoData[bingoNumber]) {
      return `&bingo=${bingoNumber}`;
    } else {
      return;
    }
  });

  return tempArray.join("");
}

export default SharePage;

```

**Comment by robinyoon-dev** [comment]
# 다운로드 성공

>npm install html2canvas

전체 코드
```javascript
import { MongoClient, ObjectId } from "mongodb";
import ShareBoard from "@/components/boards/ShareBoard";
import Layout from "@/components/layout/Layout";
import { useState, useEffect, useRef } from "react";
import styles from "@/styles/style.module.css";
import Link from "next/link";
import Grid from "@/components/layout/Grid";
import LoadingSpinner from "@/components/parts/LoadingSpinner";
import Head from "next/head";
import Confetti from "@/components/parts/Confetti";
import config from "@/config/mongo.config";
import html2canvas from "html2canvas";

function SharePage({ newBoard, bingoData, data }) {
  const [showCopiedMessage, setShowCopiedMessage] = useState(false);

  const [isLoading, setIsLoading] = useState(true);

  const divRef = useRef(null);
  const canvasRef = useRef(null);

  useEffect(() => {
    if (data !== null) {
      setIsLoading(false);
    }
  }, []);

  if (isLoading) {
    return <LoadingSpinner />;
  }

  const bingoUrl = getBingoUrl(bingoData);

  const shareUrl = `https://planbingo.vercel.app/fromLink?id=${data.id}${bingoUrl}`;

  const handleCopyClick = () => {
    navigator.clipboard.writeText(shareUrl);
    setShowCopiedMessage(true);
  };

  const downloadCanvasDiv = () => {
    const div = divRef.current;
    const canvas = canvasRef.current;

    canvas.width = div.offsetWidth;
    canvas.height = div.offsetHeight;

    html2canvas(div).then((canvas) => {
      const dataURL = canvas.toDataURL("image/png");

      const link = document.createElement("a");
      link.href = dataURL;
      link.download = "div_image.png";
      link.click();
    });
  };

  return (
    <>
      <Head>
        <title>플랜 빙고</title>
      </Head>

      <Layout>
        {newBoard.newBoard && <Confetti />}
        {data.bingoCount === 8 && <Confetti />}
        {newBoard.newBoard && (
          <div className={styles.fontSize}>
            처음으로 플랜 빙고를 만들었어요!
          </div>
        )}
        {newBoard.newBoard === false && data.bingoCount !== 8 && (
          <div className={styles.fontSize}> 👏목표를 달성했군요!👏</div>
        )}
        {data.bingoCount === 8 && (
          <div className={styles.fontSize}>
            {" "}
            🎉축하합니다! 빙고를 완성했어요!🎉
          </div>
        )}

        <canvas ref={canvasRef}></canvas>

        <div ref={divRef}>
          <ShareBoard
            bingoData={bingoData}
            main={data.main}
            title={data.title}
            value1={data.value1}
            value2={data.value2}
            value3={data.value3}
            value4={data.value4}
            value5={data.value5}
            value6={data.value6}
            value7={data.value7}
            value8={data.value8}
            value9={data.value9}
            bgColor={data.bgColor}
            cubeColor={data.cubeColor}
            bingoCount={data.bingoCount}
            patternArray={data.patternArray}
          />
        </div>

        {newBoard.newBoard && (
          <div className={styles.fontSizeS}>목표를 공유해볼까요?</div>
        )}
        {newBoard.newBoard === false && data.bingoCount !== 8 && (
          <div className={styles.fontSizeS}> 플랜 빙고를 공유해봐요😊</div>
        )}
        {data.bingoCount === 8 && (
          <div className={styles.fontSizeS}>
            {" "}
            완성한 플랜 빙고를 자랑해봐요!
          </div>
        )}

        <button onClick={downloadCanvasDiv}>이미지 저장하기</button>

        {showCopiedMessage && (
          <div className={styles.alarm}>링크가 복사되었습니다!</div>
        )}
        <Grid>
          <Link
            className={[styles.button, styles.btnNoneColor].join(" ")}
            href="/home"
          >
            홈으로
          </Link>

          <button
            onClick={handleCopyClick}
            className={[styles.button, styles.btnColor].join(" ")}
          >
            링크 복사하기
          </button>
        </Grid>
      </Layout>
    </>
  );
}

export async function getServerSideProps(ctx) {
  let newBoard, bingoData, data;

  if (ctx.query.bingoData) {
    bingoData = JSON.parse(ctx.query.bingoData);
  } else {
    bingoData = {
      bingo123: false,
      bingo456: false,
      bingo789: false,
      bingo147: false,
      bingo258: false,
      bingo369: false,
      bingo159: false,
      bingo357: false,
    };
  }

  data = JSON.parse(ctx.query.data);

  if (data.newBoard) {
    newBoard = true;
  } else {
    newBoard = false;
  }

  // fetch data from an API
  const client = await MongoClient.connect(config.mongoClient);
  const db = client.db();

  const boardsCollection = db.collection("boards");

  const board = await boardsCollection.findOne({ _id: ObjectId(data._id) });

  client.close();

  return {
    props: {
      newBoard: {
        newBoard,
      },
      bingoData: {
        bingo123: bingoData.bingo123,
        bingo456: bingoData.bingo456,
        bingo789: bingoData.bingo789,
        bingo147: bingoData.bingo147,
        bingo258: bingoData.bingo258,
        bingo369: bingoData.bingo369,
        bingo159: bingoData.bingo159,
        bingo357: bingoData.bingo357,
      },
      data: {
        id: board._id.toString(),
        user: board.user,
        main: board.main,
        title: board.title,
        value1: board.value1,
        value2: board.value2,
        value3: board.value3,
        value4: board.value4,
        value5: board.value5,
        value6: board.value6,
        value7: board.value7,
        value8: board.value8,
        value9: board.value9,
        bgColor: board.bgColor,
        cubeColor: board.cubeColor,
        bingoCount: board.bingoCount,
        patternArray: board.patternArray,
      },
    },
  };
}

export function getBingoUrl(bingoData) {
  const bingoNumbers = [
    "bingo123",
    "bingo456",
    "bingo789",
    "bingo147",
    "bingo258",
    "bingo369",
    "bingo159",
    "bingo357",
  ];

  const tempArray = bingoNumbers.map((bingoNumber) => {
    if (bingoData[bingoNumber]) {
      return `&bingo=${bingoNumber}`;
    } else {
      return;
    }
  });

  return tempArray.join("");
}

export default SharePage;

```
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/3fe49c35-9fbc-44dc-9859-65d01c5fa386)

**Comment by robinyoon-dev** [comment]
# `.titleBoardContainer` CSS 수정하기 & 해결

현재
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/84fa0700-5d5e-497e-9a0f-eedec2e753e7)

```css
.titleBoardContainer {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  text-align: center;
  position: relative;
}

```
## 문제 해결
`align-items: center;` 추가
