### ISSUE TITLE
❗새로운 보드 생성 완료 시 share할 수 있도록 바꾸자.

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#15]
## Description
현재 새로운 보드 생성 완료 시 바로 home page로 가게 만들어져있다.
이걸 share로 갈 수 있도록 바꿔야한다.
그래야 사람들이 자신의 목표를 공유할 수 있다. 

```
   router.push("/home");
```

## Todo
- [x] share 페이지로 갈 수 있도록 하기
- [x] newBoard 생성되었을 때 '축하합니다'와 같은 문구 뜨게 만들기.
- [x] check page에서 share 페이지로 이동시에는 다른 문구가 떠야한다.

## ETC
첫 보드 생성 관련 이벤트를 추가해야할까? 고려해보자.

**Comment by robinyoon-dev** [comment]
share/index.js로 가려고 했으나, share/index.js에서는 여러 데이터가 필요하기 때문에 방법을 바꾸기로 결정했다.

- [ ] newBoard와 관련된 새로운 share 페이지를 만들자!

**Comment by robinyoon-dev** [comment]
```
   const responseID = await response.json();

    const data = JSON.stringify(enteredBoardData);

    router.push(
      {
        pathname: "/share",
        query: { data },
      },
      `/share/${responseID.id}`
    );
```

여기서 문제는 `data`에는 _id값이 없다는 것이 문제다. 
_id는 mongoDB에 insert된 후 만들어지기 때문이다. 
그래서  `enteredBoardData`에는 _id가 없다. 
그러므로 `data`에 `responseID`를 추가하자.

**Comment by robinyoon-dev** [comment]
**object에 property를 추가 하는 방법**
dot notation 쓰기!

```
const myObject = {};
myObject.propertyName = propertyValue;
```

프로젝트에 다음과 같이 적용했다.
```
let tempObject = enteredBoardData;
tempObject._id = responseID.id;

const data = JSON.stringify(tempObject);
```

그리고 작동 성공.
![image](https://user-images.githubusercontent.com/107087958/226087261-9cba5f7a-63a2-4807-b21f-9faa0c206220.png)

**Comment by robinyoon-dev** [comment]
**Celebratory Confetti Effect**
https://codepen.io/jonathanbell/pen/OvYVYw

**Comment by robinyoon-dev** [comment]
Confetti effect를 적용했을 때 다음과 같은 오류가 뜬다. 
![image](https://user-images.githubusercontent.com/107087958/226147461-17094ce3-02aa-452d-9545-6db35ee68f86.png)

**Comment by robinyoon-dev** [comment]
해결
Confetti.js
```JavaScript
import classes from "./Confetti.module.css";
import { useEffect, useRef } from "react";

function Confetti() {
  const canvasRef = useRef(null);
 

  useEffect(() => {
    let W = window.innerWidth;
    let H = window.innerHeight;
    const canvas = canvasRef.current;
    const context = canvas.getContext("2d");
    const maxConfettis = 150;
    const particles = [];
    const possibleColors = [
      "DodgerBlue",
      "OliveDrab",
      "Gold",
      "Pink",
      "SlateBlue",
      "LightBlue",
      "Gold",
      "Violet",
      "PaleGreen",
      "SteelBlue",
      "SandyBrown",
      "Chocolate",
      "Crimson",
    ];

    function randomFromTo(from, to) {
      return Math.floor(Math.random() * (to - from + 1) + from);
    }

    function confettiParticle() {
      this.x = Math.random() * W; // x
      this.y = Math.random() * H - H; // y
      this.r = randomFromTo(11, 33); // radius
      this.d = Math.random() * maxConfettis + 11;
      this.color =
        possibleColors[Math.floor(Math.random() * possibleColors.length)];
      this.tilt = Math.floor(Math.random() * 33) - 11;
      this.tiltAngleIncremental = Math.random() * 0.07 + 0.05;
      this.tiltAngle = 0;

      this.draw = function () {
        context.beginPath();
        context.lineWidth = this.r / 2;
        context.strokeStyle = this.color;
        context.moveTo(this.x + this.tilt + this.r / 3, this.y);
        context.lineTo(this.x + this.tilt, this.y + this.tilt + this.r / 5);
        return context.stroke();
      };
    }
    function Draw() {
      const results = [];

      // Magical recursive functional love
      requestAnimationFrame(Draw);

      context.clearRect(0, 0, W, window.innerHeight);

      for (var i = 0; i < maxConfettis; i++) {
        results.push(particles[i].draw());
      }

      let particle = {};
      let remainingFlakes = 0;
      for (var i = 0; i < maxConfettis; i++) {
        particle = particles[i];

        particle.tiltAngle += particle.tiltAngleIncremental;
        particle.y += (Math.cos(particle.d) + 3 + particle.r / 2) / 2;
        particle.tilt = Math.sin(particle.tiltAngle - i / 3) * 15;

        if (particle.y <= H) remainingFlakes++;

        // If a confetti has fluttered out of view,
        // bring it back to above the viewport and let if re-fall.
        if (particle.x > W + 30 || particle.x < -30 || particle.y > H) {
          particle.x = Math.random() * W;
          particle.y = -30;
          particle.tilt = Math.floor(Math.random() * 10) - 20;
        }
      }

      return results;
    }

    window.addEventListener(
      "resize",
      function () {
        W = window.innerWidth;
        H = window.innerHeight;
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
      },
      false
    );
    // Push new confetti objects to `particles[]`
    for (var i = 0; i < maxConfettis; i++) {
      particles.push(new confettiParticle());
    }

    // Initialize
    canvas.width = W;
    canvas.height = H;
    Draw();
  }, []);

  return <canvas ref={canvasRef} className={classes.canvas}></canvas>;
}

export default Confetti;
```
![image](https://user-images.githubusercontent.com/107087958/226148260-428660a7-454a-447a-bc53-186f63ecabea.png)


***`useRef`***
ref의 가장 기본적인 기능은 다른 DOM 요소에 접근해서 그것들로 작업할 수 있게 해주는 것이다.
ref를 사용하여 마지막에 렌더링되는 HTML 요소들과 다른 자바스크립트 코드의 연결을 설정할 수 있다.

**Comment by robinyoon-dev** [comment]
플랜 빙고가 처음 만들어진 경우, 8빙고를 한 경우, 그 외의 경우를 나눠서 이펙트와 컴포넌트를 추가했다.
```
        {newBoard.newBoard && <Confetti />}
        {data.bingoCount === 8 && <Confetti />}
        {newBoard.newBoard && (
          <div className={styles.fontSize}>
            처음으로 플랜 빙고를 만들었어요!
          </div>
        )}
        {newBoard.newBoard === false && data.bingoCount !== 8 && (
          <div className={styles.fontSize}> 👏목표를 달성했군요!👏</div>
        )}
        {data.bingoCount === 8 && (
          <div className={styles.fontSize}> 🎉축하합니다! 빙고를 완성했어요!🎉</div>
        )}
```
