### ISSUE TITLE
UX/UI 피드백: CSS 수정

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#20]
## Description
한 유저에게 UX/UI 관련 피드백을 받았다.

## Todo
- [x] 회원가입/ 로그인 페이지 - input에 입력한 폰트 크기를 작게 만들자. 한 눈에 들어오도록.
![image](https://user-images.githubusercontent.com/107087958/226491153-b782fdc5-d7d2-43e7-97ca-4a29b110e3dd.png)

- [x] 튜토리얼 페이지 - 내용 폰트 크기 키우고, next 버튼 안에 패딩 넣어주기.
![image](https://user-images.githubusercontent.com/107087958/226491321-7bf89874-ffa8-43c1-828c-1f12d05a8c3d.png)

- [x] 메뉴 - 이메일 주소가 네모 안에 다 들어올 수 있도록 수정하기.
![image](https://user-images.githubusercontent.com/107087958/226491382-3929c8e6-81d2-469e-81c5-2153bda8768c.png)

- [x] 체크 페이지 - 안내문이 한 문장으로 나올 수 있도록 수정하기.
![image](https://user-images.githubusercontent.com/107087958/226491430-ea0711ec-d0d0-4430-ae1b-6d8c5775d00f.png)

-  [x] 체크 페이지 - 큐브의 그림자 효과를 아래의 조언대로 수정. 
![image](https://user-images.githubusercontent.com/107087958/226491504-6eecc121-9d4e-4212-83b5-f9f378727738.png)

**Comment by robinyoon-dev** [comment]
### 문제1
![image](https://user-images.githubusercontent.com/107087958/227105288-d5806c42-3ca0-4dd8-bc33-2621ec2e6df2.png)

현재 "이루고 싶은 목표로 9칸을 모두 채워봐요"가 한 줄로 나타나게 한 상태이다.
나는 여기에 '줄바꿈'을 넣어서 두 줄로 보이게 만들고 싶다.


내가 쓴 코드는 아래와 같은데 이러면 오류가 뜬다. 어떻게 해야 이 문제를 해결할 수 있을까?
```
 <Description text={"이루고 싶은 목표로"+{/n}+"9칸을 모두 채워봐요"} />
```

**Comment by robinyoon-dev** [comment]
### 문제1 -풀이 과정

우선 나는 중대한 실수를 했다. **이스케이프문자는 \를 사용하는 거였지!**

그러나 이스케이프문자를 넣어도 한 줄로 나온다.

내가 쓴 코드
```
        <Description text={"이루고 싶은 목표로 \n 9칸을 모두 채워봐요"} />
```

결과 
![image](https://user-images.githubusercontent.com/107087958/227105988-4f392907-169d-4571-ab7c-ef4b951ec2f9.png)

**Comment by robinyoon-dev** [comment]
## 문제1 해결

**`<br>` 태그를 사용하자!**

```
        <Description>
          이루고 싶은 목표로
          <br />
          9칸을 모두 채워봐요
        </Description>
```

**Comment by robinyoon-dev** [comment]
### 메뉴 - 이메일 주소가 네모 안에 다 들어올 수 있도록 수정하기 - 해결 방법
**word-break: break-all; 추가**

**Comment by robinyoon-dev** [comment]
ver.0.1.4
