### ISSUE TITLE
생각해보기: 로딩 시 로딩스피너를 넣을 수 있는 방법이 없을까?

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#21]
## Description
데이터를 불러올 때에는 로딩스피너 컴포넌트를 넣어줬다.
그러나 그외에도 로딩 때마다 (예: 클릭 후 페이지 이동하는 경우) 로딩스피너를 어떻게 해야 유저에게 보여줄지 모르겠다.
이 방법에 대해 생각해보자.

## Todo
- [x] 로딩스피너를 어떻게 해야 보여줄 수 있을지 방법 생각해보기.
- [x] 프로젝트에 적용하기.
- [x] 화면 전환 시 로딩스피너 적용
- [x] 로그인 및 회원가입 시 로딩 스피너 적용

**Comment by robinyoon-dev** [comment]
### View Transitions API
https://www.youtube.com/watch?v=ObT87Xu_CO0&t=78s

화면 사이 이동시 애니메이션.


![image](https://user-images.githubusercontent.com/107087958/227392976-7e0fdfce-3281-4daf-8da2-cd7aaa9afeb6.png)
![image](https://user-images.githubusercontent.com/107087958/227393016-de668d9c-bcf0-4d24-b501-f2ab0ea1ff24.png)

**그러나 현재 이 API는 실험단계라 크롬과 안드로이드용 크롬에서만 가능하다.**

**Comment by robinyoon-dev** [comment]
# HTTP response status codes 102를 사용해서 가능할까?
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/1f211581-9cc2-4975-92e0-3198a943f365)


### 그런데 deprecated가 된 상태 코드이다....
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/2d3bc90b-6f6b-4424-9510-039e7aae7299)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102


+ 그리고 애초에 활용하기도 어려웠다.

**Comment by robinyoon-dev** [comment]
# _app,js에서 router를 활용해 페이지 전환 시 로딩 스피너 추가 성공

_app.js
```javascript
import "@/styles/globals.css";
import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

import LoadingSpinner from "@/components/parts/LoadingSpinner";

function App({ Component, pageProps }) {
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const handleStart = () => setIsLoading(true);
    const handleComplete = () => setIsLoading(false);
    const handleError = () => setIsLoading(false);

    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleComplete);
    router.events.on("routeChangeError", handleError);

    return () => {
      router.events.off("routeChangeStart", handleStart);
      router.events.off("routeChangeComplete", handleComplete);
      router.events.off("routeChangeError", handleError);
    };
  }, [router.events]);

  return (
    <>
      {" "}
      <Head>
       {/*생략*/}
      </Head>
      {isLoading && (
        <body>
          <LoadingSpinner />
        </body>
      )}
      <Component {...pageProps} />
    </>
  );
}

export default App;

```

**Comment by robinyoon-dev** [comment]
# ver.0.1.11에서 리팩토링
```
      {isLoading ? (
        <body>
          <LoadingSpinner />
        </body>
      ) : (
        <Component {...pageProps} />
      )}
```

**Comment by robinyoon-dev** [comment]
# fetching data시 작은 로딩 스피너 보여주기

예시 코드
sign-in/index.js
```javascript
import LoginForm from "@/components/user/LoginForm";
import { useRouter } from "next/router";
import { useState } from "react";
import Cookies from "js-cookie";
import Head from "next/head";
import LoadingSpinnerSmall from "@/components/parts/LoadingSpinnerSmall";
function SignInPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [isFailed, setIsFailed] = useState(false);

  async function loginHandler(loginData) {
    setIsLoading(true);

    async function loadData(loginData) {
      const userEmail = loginData.email;
      const password = loginData.password;

      const response = await fetch(
        `/api/check-login?id=${userEmail}&pw=${password}`
      );
      const isLoginSuccess = await response.json();
      return isLoginSuccess;
    }

    loadData(loginData).then((isLoginSuccess) => {
      setIsLoading(false);
      if (isLoginSuccess.result) {
        Cookies.set("user", JSON.stringify(isLoginSuccess.userData));

        router.push("/home");
      } else {
        setIsFailed(true);
      }
    });
  }

  return (
    <>
      <Head>
        <title>플랜 빙고</title>
      </Head>
      {isLoading && (<LoadingSpinnerSmall/>)}
      <LoginForm onLogin={loginHandler} isFailed={isFailed} />
    </>
  );
}

export default SignInPage;

```
