### ISSUE TITLE
UI 개선: 버튼 hover 관련

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#34]
## Description
share 페이지 버튼 hover UI 개선하자. (transition 제대로 넣기)

## Todo
- [x] share 페이지 버튼 hover UI 개선하자.
- [x] 다른 페이지의 버튼도 살펴본 후 UI 개선.
- [x] 리팩토링: 중복성 제거

**Comment by robinyoon-dev** [comment]
# 문제 있는 버튼
- [x] 튜토리얼 step2 버튼
- [x] newBoard 버튼 transition이 부드럽지 않다.
- [x]  newBoard 완성 버튼 포인터
- [x]  home(보드 없을 때) - transition
- [x]  home - transition, pointer
- [x]  fromLink - transition, pointer
- [x]  edit - transition, pointer
- [x]  check - hover 문제 , transition, pointer

**Comment by robinyoon-dev** [comment]
# Button 컴포넌트 적용
- [x] newBoard 
- [x]  home 
- [x]  fromLink 
- [x]  edit 
- [x]  check

**Comment by robinyoon-dev** [comment]
# Button Component
```javascript
import styles from "@/styles/style.module.css";
import btnStyles from "@/components/layout/Button.module.css";

function Button(props) {
  let classColor;

  if (props.btnColor === "btnNoneColor") {
    classColor = "btnNoneColor";
  } else {
    classColor = "btnColor";
  }

  return (
    <button
      type={props.type}
      className={[btnStyles.button, styles[classColor]].join(" ")}
      onClick={props.onClickHandler}
    >
      <p>{props.description}</p>
    </button>
  );
}

export default Button;

```
