### ISSUE TITLE
버튼이 focus 되지 않는 문제

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#4]
## Description
피드백 내용: 드로워 메뉴 여는 버튼이 button 요소가 아닌 건지, focus가 되지 않더라구요.

## Todo
- [x] 프로젝트 내의 모든 버튼이 focus 되는지 확인.
- [x] focus 되도록 만들기.
- [ ] #22
- [ ] 메뉴-로그아웃 버튼 tab key 클릭 시 focus 되도록 만들기.

**Comment by robinyoon-dev** [comment]
프로젝트 내에서 focus 안 되는 요소
- 메뉴 여는 버튼
- 메뉴 닫는 버튼
- 메뉴: 로그아웃
- edit page: 선택되지 않는 색깔 요소
- check page: 보드 내의 큐브

**Comment by robinyoon-dev** [comment]
ver.0.1.4 웹 접근성 테스트 결과
https://github.com/robinyoon-dev/plan-bingo-project/issues/2#issuecomment-1482096546

**Comment by robinyoon-dev** [comment]
**메뉴 여는 버튼**
기존에는 svg 태그에서 직접 onClick을 적용했는데, 다음과 같이 바꿨다.

```HTML
        <button
          type="button"
          className={classes.menuBox}
          onClick={openMenuHandler}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            fill="currentColor"
            class="bi bi-list"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
            />
          </svg>
        </button>
```

**Comment by robinyoon-dev** [comment]
## Edit Page에서 선택되지 않은 radio type input을 focus 하게 만든 법

주요 코드
```HTML
          data-focus-group="bgColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              document.querySelector(`[data-focus-group="cubeColor"]`).focus();
            }
          }}

          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              event.target.nextSibling.focus();
            }
          }}

          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              document.querySelector(`button[type="button"]`).focus();
            }
          }}

```

해당 부분 전체 코드
```HTML
      {/* 배경 색깔 */}
      <LayoutStyle title="배경 색깔">
        <input
          className={[styles.input, styles.bgColor1].join(" ")}
          type="radio"
          name="bgColor"
          value="bgColor1"
          checked={selectedBg === "bgColor1"}
          onChange={BgStyleChangeHandler}
          data-focus-group="bgColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              event.target.nextSibling.focus();
            }
          }}
        />
        <input
          className={[styles.input, styles.bgColor2].join(" ")}
          type="radio"
          name="bgColor"
          value="bgColor2"
          checked={selectedBg === "bgColor2"}
          onChange={BgStyleChangeHandler}
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              document.querySelector(`[data-focus-group="cubeColor"]`).focus();
             
            }
          }}
        />  
      </LayoutStyle>

      {/* 큐브 색깔 */}
      <LayoutStyle title="큐브 색깔">
        <input
          className={[styles.input, styles.cubeColor1].join(" ")}
          type="radio"
          name="cubeColor"
          value="cubeColor1"
          checked={selectedCube === "cubeColor1"}
          onChange={CubeStyleChangeHandler}
          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              event.target.nextSibling.focus();
            }
          }}
        />
        <input
          className={[styles.input, styles.cubeColor2].join(" ")}
          type="radio"
          name="cubeColor"
          value="cubeColor2"
          checked={selectedCube === "cubeColor2"}
          onChange={CubeStyleChangeHandler}
          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              event.target.nextSibling.focus();
            }
          }}
        />
        <input
          className={[styles.input, styles.cubeColor3].join(" ")}
          type="radio"
          name="cubeColor"
          value="cubeColor3"
          checked={selectedCube === "cubeColor3"}
          onChange={CubeStyleChangeHandler}
          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              event.target.nextSibling.focus();
            }
          }}
        />
        <input
          className={[styles.input, styles.cubeColor4].join(" ")}
          type="radio"
          name="cubeColor"
          value="cubeColor4"
          checked={selectedCube === "cubeColor4"}
          onChange={CubeStyleChangeHandler}
          data-focus-group="cubeColor"
          onKeyDown={(event) => {
            if (event.key === "Tab") {
              event.preventDefault();
              document.querySelector(`button[type="button"]`).focus();
            }
          }}
        />
      </LayoutStyle>

      {/* 버튼 */}
      <Grid>
        <button
          type="button"
          className={[styles.button, styles.btnNoneColor].join(" ")}
          onClick={goToHomeHandler}
        >
          홈으로
        </button>
        <button
          type="submit"
          className={[styles.button, styles.btnColor].join(" ")}
        >
          완성
        </button>
      </Grid>
```

![image](https://user-images.githubusercontent.com/107087958/227430634-5c1d78b8-0e7b-4d24-ba3b-8387f752251e.png)

선택되지 않은 색깔도 tab key로 focus 할 수 있게 되었다.

**Comment by robinyoon-dev** [comment]
## check page: 보드 내의 큐브에 tab key로 focus하는 방법

```HTML
    <div
      className={[
        styles.borderStyle,
        styles.textareaWrapper,
        styles[ColorClassName],
        classes.textareaWrapperHover,
        firstCheck
          ? classes.disabled
          : checkToggle
          ? " "
          : classes.whiteBackground,
        isModified ? classes.cubeModified : " ",
      ].join(" ")}
      tabIndex={0}
      onKeyDown={(event) => {
        if ((event.key === "Enter" || event.key === " ") && !firstCheck) {
          event.preventDefault();
          onClickHandler();
        }
      }}
      onClick={onClickHandler}
    >
      <div className={styles.textInputCube}>{props.children}</div>
    </div>
```


- `tabIndex={0}`추가하여 tab key로 focus 가능하게 만들었다.
- onKeyDown으로 엔터를 누르거나 스페이스바를 눌렀을 때 onClickHandler가 작동하도록 만들었다.
