### ISSUE TITLE
CSS 관련된 여러 피드백과 기타 피드백

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#6]
## Description
한 유저로부터 상세한 피드백을 받았다. 
다음과 같은 사항을 수정하도록 하자.

## Todo
- [x] 비활성화된 버튼에는 hover 효과를 없애자. 
![image](https://user-images.githubusercontent.com/107087958/225465640-80cacd0d-a99d-4e63-b3f1-cffd4553e1b0.png)

- [x] 로그인, 회원가입 페이지를 번갈아 움직이면 콘솔에 로그가 찍힌다. 없애자.
![image](https://user-images.githubusercontent.com/107087958/225465753-a408a4d2-7c6e-4e6f-95f8-e6da78135257.png)

- [x] #18
![image](https://user-images.githubusercontent.com/107087958/225465826-c0a90563-558b-4be9-84f3-e6e532dff4e8.png)

- [x]  뷰포트 폭 900px 언저리에서 입력란이 좌정렬되는 현상 해결.
![image](https://user-images.githubusercontent.com/107087958/225465947-f5fb5a45-2035-4691-9892-0baeb14b86a5.png)

**Comment by robinyoon-dev** [comment]
특정 뷰포트 너비에서 우측 상단 버튼이 가려지는 문제에 관한 메모
- 너비 701px  ~ 1023px까지 문제 발생.
- 처음 페이지에서만 문제가 생긴다.

**Comment by robinyoon-dev** [comment]
추가로 newBoard Page에서 console log 찍히는 문제 해결.
![image](https://user-images.githubusercontent.com/107087958/225479670-4d7431c7-1bc3-4c12-b59b-ef3bdb51d77e.png)

**Comment by robinyoon-dev** [comment]
ver. 0.0.1

**Comment by robinyoon-dev** [comment]
.
